import { Application } from '../declarations';
import users from './users/users.service';
import appointments from './appointments/appointments.service';
import patients from './patients/patients.service';
import personalData from './personal-data/personal-data.service';
import contactData from './contact-data/contact-data.service';
import mdSettings from './md-settings/md-settings.service';
import encounters from './encounters/encounters.service';
import userPersonalData from './user-personal-data/user-personal-data.service';
import userContactData from './user-contact-data/user-contact-data.service';
import patientPersonalData from './patient-personal-data/patient-personal-data.service';
import patientContactData from './patient-contact-data/patient-contact-data.service';
import roles from './roles/roles.service';
import studies from './studies/studies.service';
import studyResults from './study-results/study-results.service';
import icd10 from './icd-10/icd-10.service';
import laboratories from './laboratories/laboratories.service';
import medications from './medications/medications.service';
import timeOffEvents from './time-off-events/time-off-events.service';
import prepagas from './prepagas/prepagas.service';
import referringDoctors from './referring-doctors/referring-doctors.service';
import userRoles from './user-roles/user-roles.service';
import profile from './profile/profile.service';
import passkeyCredentials from './passkey-credentials/passkey-credentials.service';
import webauthn from './webauthn/webauthn.service';
import organizations from './organizations/organizations.service';
import organizationUsers from './organization-users/organization-users.service';
import organizationPatients from './organization-patients/organization-patients.service';
import mailer from './mailer/mailer.service';
import invites from './invites/invites.service';
import signingCertificates from './signing-certificates/signing-certificates.service';
import documentSignatures from './document-signatures/document-signatures.service';
import documentVerification from './document-verification/document-verification.service';
import signedExports from './signed-exports/signed-exports.service';
import stats from './stats/stats.service';
import practitionerVerification from './practitioner-verification/practitioner-verification.service';
import encounterAiChat from './encounter-ai-chat/encounter-ai-chat.service';
import encounterAiChatMessages from './encounter-ai-chat-messages/encounter-ai-chat-messages.service';
import llmApiKeys from './llm-api-keys/llm-api-keys.service';
import llmModels from './llm-models/llm-models.service';
import accounting from './accounting/accounting.service';
import accountingSettings from './accounting-settings/accounting-settings.service';
import practiceCosts from './practice-costs/practice-costs.service';
import prescriptions from './prescriptions/prescriptions.service';
import recetario from './recetario/recetario.service';
import whatsapp from './whatsapp/whatsapp.service';
import whatsappInstances from './whatsapp-instances/whatsapp-instances.service';
import fileUploads from './file-uploads/file-uploads.service';
import urlFetch from './url-fetch/url-fetch.service';
import sharedEncounterAccess from './shared-encounter-access/shared-encounter-access.service';
import accessLogs from './access-logs/access-logs.service';
import identityVerifications from './identity-verifications/identity-verifications.service';
import patientOtp from './patient-otp/patient-otp.service';
import booking from './booking/booking.service';
import encounterChainVerification from './encounter-chain-verification/encounter-chain-verification.service';
import accessLogChainVerification from './access-log-chain-verification/access-log-chain-verification.service';
import logout from './logout/logout.service';
// Don't remove this comment. It's needed to format import lines nicely.

export default function (app: Application): void {
  app.configure(users);
  app.configure(appointments);
  app.configure(patients);
  app.configure(personalData);
  app.configure(contactData);
  app.configure(mdSettings);
  app.configure(encounters);
  app.configure(userPersonalData);
  app.configure(userContactData);
  app.configure(patientPersonalData);
  app.configure(patientContactData);
  app.configure(roles);
  app.configure(studies);
  app.configure(studyResults);
  app.configure(icd10);
  app.configure(laboratories);
  app.configure(medications);
  app.configure(timeOffEvents);
  app.configure(prepagas);
  app.configure(referringDoctors);
  app.configure(userRoles);
  app.configure(profile);
  app.configure(passkeyCredentials);
  app.configure(webauthn);
  app.configure(organizations);
  app.configure(organizationUsers);
  app.configure(organizationPatients);
  app.configure(mailer);
  app.configure(invites);
  app.configure(signingCertificates);
  app.configure(documentSignatures);
  app.configure(documentVerification);
  app.configure(signedExports);
  app.configure(stats);
  app.configure(practitionerVerification);
  app.configure(encounterAiChat);
  app.configure(encounterAiChatMessages);
  app.configure(llmApiKeys);
  app.configure(llmModels);
  app.configure(accounting);
  app.configure(accountingSettings);
  app.configure(practiceCosts);
  app.configure(prescriptions);
  app.configure(recetario);
  app.configure(whatsapp);
  app.configure(whatsappInstances);
  app.configure(fileUploads);
  app.configure(urlFetch);
  app.configure(sharedEncounterAccess);
  app.configure(accessLogs);
  app.configure(identityVerifications);
  app.configure(patientOtp);
  app.configure(booking);
  app.configure(encounterChainVerification);
  app.configure(accessLogChainVerification);
  app.configure(logout);
}
