export {
  evolutionAdapter,
  reasonForConsultationAdapter,
  currentIllnessAdapter,
  personalHistoryAdapter,
  drugAllergyAdapter,
  familyHistoryAdapter,
  medicationHistoryAdapter,
  housingHistoryAdapter,
  generalAllergyAdapter,
  asthmaAdapter,
  cardiologyAdapter,
  habitsAdapter,
  occupationalHistoryAdapter,
} from '@athelas/encounter-schemas';
